preset: klausmeier_topography

parameters:
  a:
    sample: uniform
    min: 1.0
    max: 1.2
  m:
    sample: uniform
    min: 0.56
    max: 0.68
  D:
    sample: uniform
    min: 1.7
    max: 3.0
  Dn:
    sample: uniform
    min: 0.7
    max: 1.2
  V:
    sample: uniform
    min: 86.0
    max: 126.0

coefficients:
  topography:
    type: affine
    params:
      x:
        sample: uniform
        min: 0.14
        max: 0.22
      y:
        sample: uniform
        min: 0.03
        max: 0.08

domain:
  allow_sampling: true
  type: parallelogram
  origin: [0.0, 0.0]
  axis_x:
    - sample: uniform
      min: 96.0
      max: 112.0
    - sample: uniform
      min: -6.0
      max: 6.0
  axis_y:
    - sample: uniform
      min: 18.0
      max: 32.0
    - sample: uniform
      min: 96.0
      max: 112.0
  mesh_resolution:
    - sample: randint
      min: 128
      max: 152
    - sample: randint
      min: 128
      max: 152

time:
  dt: 0.01
  t_end: 38.0

inputs:
  w:
    initial_condition:
      type: constant
      params:
        value:
          sample: uniform
          min: 0.92
          max: 1.14
  n:
    initial_condition:
      type: gaussian_noise
      params:
        mean:
          sample: uniform
          min: 0.82
          max: 1.08
        std:
          sample: uniform
          min: 0.14
          max: 0.3

boundary_conditions:
  w:
    $ref: boundary_field.scalar.full_periodic_2d
  n:
    $ref: boundary_field.scalar.full_periodic_2d

solver:
  $ref: solver.profile.constant_lhs_scalar_nonsymmetric

output:
  $ref: output.template.scalar_wn_topography
  formats: [numpy, gif]
  resolution: [160, 160]
  num_frames: 121

seed: 42
