preset: cgl
parameters:
  D_r:
    sample: uniform
    min: 0.28
    max: 0.52
  D_i:
    sample: uniform
    min: -1.8
    max: -0.95
  a_r:
    sample: uniform
    min: 0.55
    max: 0.9
  a_i:
    sample: uniform
    min: -0.9
    max: -0.25
  b_r:
    sample: uniform
    min: -0.9
    max: -0.55
  b_i:
    sample: uniform
    min: -1.45
    max: -0.72
  theta:
    sample: uniform
    min: 0.54
    max: 0.66
domain:
  allow_sampling: true
  type: parallelogram
  origin: [0.0, 0.0]
  axis_x:
    - sample: uniform
      min: 48.0
      max: 62.0
    - sample: uniform
      min: -6.0
      max: 6.0
  axis_y:
    - sample: uniform
      min: 20.0
      max: 34.0
    - sample: uniform
      min: 54.0
      max: 68.0
  mesh_resolution: [144, 160]
time:
  dt: 0.1
  t_end: 30.0
inputs:
  u:
    initial_condition:
      type: quadrants
      params:
        split:
          - sample: uniform
            min: 24.0
            max: 34.0
          - sample: uniform
            min: 24.0
            max: 36.0
        region_values:
          "00":
            sample: uniform
            min: 0.7
            max: 1.05
          "01":
            sample: uniform
            min: -0.95
            max: -0.55
          "10":
            sample: uniform
            min: 0.15
            max: 0.55
          "11":
            sample: uniform
            min: -0.35
            max: 0.15
  v:
    initial_condition:
      type: quadrants
      params:
        split:
          - sample: uniform
            min: 24.0
            max: 34.0
          - sample: uniform
            min: 24.0
            max: 36.0
        region_values:
          "00":
            sample: uniform
            min: -0.25
            max: 0.25
          "01":
            sample: uniform
            min: 0.55
            max: 1.0
          "10":
            sample: uniform
            min: -1.0
            max: -0.55
          "11":
            sample: uniform
            min: 0.2
            max: 0.65
boundary_conditions:
  u:
    $ref: boundary_field.scalar.full_periodic_2d
  v:
    $ref: boundary_field.scalar.full_periodic_2d
output:
  $ref: output.template.cgl
  formats: [numpy, gif]
  resolution: [160, 160]
  num_frames: 55
solver:
  $ref: solver.profile.nonlinear_mixed_direct
seed: 242
