preset: helmholtz
parameters:
  kappa: 1.0
  k: 2.0
  f_amplitude: 1.0
domain:
  type: box
  size: [1.0, 1.0, 1.0]
  mesh_resolution: [16, 16, 16]
inputs:
  u:
    source:
      type: sine_product
      params:
        amplitude: "param:f_amplitude"
        kx: 1
        ky: 1
        kz: 1
boundary_conditions:
  u:
    x-:
      - operator: dirichlet
        value: 0.0
    x+:
      - operator: dirichlet
        value: 0.0
    y-:
      - operator: dirichlet
        value: 0.0
    y+:
      - operator: dirichlet
        value: 0.0
    z-:
      - operator: dirichlet
        value: 0.0
    z+:
      - operator: dirichlet
        value: 0.0
solver:
  strategy: stationary_indefinite_direct
  serial:
    ksp_type: preonly
    pc_type: lu
  mpi:
    ksp_type: preonly
    pc_type: lu
    pc_factor_mat_solver_type: mumps
    mat_mumps_icntl_14: 80
    mat_mumps_icntl_24: 1
    mat_mumps_icntl_25: 0
    ksp_error_if_not_converged: 1
output:
  resolution: [16, 16, 16]
  num_frames: 1
  formats: [numpy, gif]
  fields:
    u: scalar
seed: 42
