preset: burgers
parameters:
  nu:
    sample: uniform
    min: 0.0035
    max: 0.0075
domain:
  allow_sampling: true
  type: rectangle
  size:
  - sample: uniform
    min: 0.96
    max: 1.08
  - sample: uniform
    min: 0.96
    max: 1.08
  mesh_resolution:
  - sample: randint
    min: 128
    max: 148
  - sample: randint
    min: 128
    max: 148
time:
  dt: 0.0035
  t_end: 0.7
inputs:
  velocity:
    source:
      type: none
      params: {}
    initial_condition:
      components:
        x:
          type: sine_waves
          params:
            background: 0.0
            modes:
            - amplitude:
                sample: uniform
                min: 0.65
                max: 1.05
              cycles:
              - 0
              - 2
              phase:
                sample: uniform
                min: 0.0
                max: 6.283185
              angle: 0.0
            - amplitude:
                sample: uniform
                min: 0.2
                max: 0.55
              cycles:
              - sample: uniform
                min: 2.0
                max: 4.0
              - sample: uniform
                min: 1.0
                max: 3.0
              phase:
                sample: uniform
                min: 0.0
                max: 6.283185
              angle:
                sample: uniform
                min: -0.75
                max: 0.75
        y:
          type: sine_waves
          params:
            background: 0.0
            modes:
            - amplitude:
                sample: uniform
                min: -1.05
                max: -0.65
              cycles:
              - 2
              - 0
              phase:
                sample: uniform
                min: 0.0
                max: 6.283185
              angle: 0.0
            - amplitude:
                sample: uniform
                min: -0.55
                max: -0.2
              cycles:
              - sample: uniform
                min: 1.0
                max: 3.0
              - sample: uniform
                min: 2.0
                max: 4.0
              phase:
                sample: uniform
                min: 0.0
                max: 6.283185
              angle:
                sample: uniform
                min: -0.75
                max: 0.75
boundary_conditions:
  velocity:
    $ref: boundary_field.vector.full_periodic_2d
stochastic:
  states:
    velocity:
      coupling: additive
      intensity: 0.015
solver:
  $ref: solver.profile.nonlinear_mixed_direct
output:
  resolution:
  - 144
  - 144
  num_frames: 41
  formats:
  - numpy
  - gif
  fields:
    velocity:
      mode: components
seed: 42
