preset: burgers
parameters:
  nu: 0.003
domain:
  allow_sampling: true
  type: rectangle
  size:
  - sample: uniform
    min: 0.94
    max: 1.10
  - sample: uniform
    min: 0.94
    max: 1.10
  mesh_resolution:
  - sample: randint
    min: 128
    max: 152
  - sample: randint
    min: 128
    max: 152
time:
  dt: 0.004
  t_end: 0.85
inputs:
  velocity:
    source:
      type: none
      params: {}
    initial_condition:
      components:
        x:
          type: sine_waves
          params:
            background: 0.0
            modes:
            - amplitude:
                sample: uniform
                min: 0.9
                max: 1.25
              cycles:
              - 0
              - 2
              phase:
                sample: uniform
                min: 0.0
                max: 6.283185
              angle: 0.0
            - amplitude:
                sample: uniform
                min: -0.35
                max: 0.35
              cycles:
              - sample: uniform
                min: 1.0
                max: 2.0
              - sample: uniform
                min: 1.0
                max: 3.0
              phase:
                sample: uniform
                min: 0.0
                max: 6.283185
              angle:
                sample: uniform
                min: -0.55
                max: 0.55
        y:
          type: sine_waves
          params:
            background: 0.0
            modes:
            - amplitude:
                sample: uniform
                min: -1.25
                max: -0.9
              cycles:
              - 2
              - 0
              phase:
                sample: uniform
                min: 0.0
                max: 6.283185
              angle: 0.0
            - amplitude:
                sample: uniform
                min: -0.35
                max: 0.35
              cycles:
              - sample: uniform
                min: 1.0
                max: 3.0
              - sample: uniform
                min: 1.0
                max: 2.0
              phase:
                sample: uniform
                min: 0.0
                max: 6.283185
              angle:
                sample: uniform
                min: -0.55
                max: 0.55
boundary_conditions:
  velocity:
    $ref: boundary_field.vector.full_periodic_2d
solver:
  $ref: solver.profile.nonlinear_mixed_direct
output:
  resolution:
  - 144
  - 144
  num_frames: 43
  formats:
  - numpy
  - gif
  fields:
    velocity:
      mode: components
seed: 42
