preset: swift_hohenberg
parameters:
  r:
    sample: uniform
    min: -0.16
    max: 0.04
  q0:
    sample: uniform
    min: 0.72
    max: 0.98
  alpha:
    sample: uniform
    min: 1.55
    max: 2.05
  beta:
    sample: uniform
    min: -1.1
    max: -0.65
  gamma:
    sample: uniform
    min: -0.34
    max: -0.1
  theta:
    sample: uniform
    min: 0.55
    max: 0.65
  domain_center_x:
    sample: uniform
    min: -1.0
    max: 1.0
  domain_center_y:
    sample: uniform
    min: -1.0
    max: 1.0
coefficients:
  velocity:
    components:
      x:
        type: affine
        params:
          x:
            sample: uniform
            min: -0.025
            max: -0.006
          y:
            sample: uniform
            min: -0.04
            max: 0.04
      y:
        type: affine
        params:
          x:
            sample: uniform
            min: -0.04
            max: 0.04
          y:
            sample: uniform
            min: 0.006
            max: 0.025
domain:
  allow_sampling: true
  type: annulus
  center: ["param:domain_center_x", "param:domain_center_y"]
  inner_radius:
    sample: uniform
    min: 7.0
    max: 10.0
  outer_radius:
    sample: uniform
    min: 21.0
    max: 25.0
  mesh_size:
    sample: uniform
    min: 0.22
    max: 0.29
time:
  dt: 0.1
  t_end: 22.0
inputs:
  u:
    initial_condition:
      type: radial_cosine
      params:
        base:
          sample: uniform
          min: -0.02
          max: 0.02
        amplitude:
          sample: uniform
          min: 0.24
          max: 0.5
        frequency:
          sample: uniform
          min: 0.58
          max: 0.95
        center:
        - param:domain_center_x
        - param:domain_center_y
boundary_conditions:
  u:
    inner:
    - operator: simply_supported
    outer:
    - operator: simply_supported
output:
  $ref: output.template.scalar_u
  formats: [numpy, gif]
  resolution: [160, 160]
  num_frames: 73
solver:
  $ref: solver.profile.nonlinear_mixed_direct
seed: 5280
