preset: brusselator
parameters:
  Du:
    sample: uniform
    min: 0.035
    max: 0.052
  Dv:
    sample: uniform
    min: 0.98
    max: 1.45
  a:
    sample: uniform
    min: 1.45
    max: 1.75
  b:
    sample: uniform
    min: 2.05
    max: 2.7
  domain_center_x:
    sample: uniform
    min: -0.5
    max: 0.5
  domain_center_y:
    sample: uniform
    min: -0.5
    max: 0.5
  u_wall_value:
    sample: uniform
    min: 1.2
    max: 1.45
  v_wall_value:
    sample: uniform
    min: 1.05
    max: 1.45
domain:
  allow_sampling: true
  type: disk
  center:
  - param:domain_center_x
  - param:domain_center_y
  radius:
    sample: uniform
    min: 15.0
    max: 18.5
  mesh_size:
    sample: uniform
    min: 0.23
    max: 0.285
time:
  dt: 0.035
  t_end: 24.0
inputs:
  u:
    initial_condition:
      type: gaussian_blobs
      params:
        background:
          sample: uniform
          min: 1.45
          max: 1.7
        generators:
        - count:
            sample: randint
            min: 5
            max: 8
          amplitude:
            sample: uniform
            min: 0.08
            max: 0.24
          sigma:
            sample: uniform
            min: 0.8
            max: 1.6
          aspect_ratio:
            sample: uniform
            min: 1.0
            max: 2.8
          center:
          - sample: uniform
            min: -10.5
            max: 10.5
          - sample: uniform
            min: -10.5
            max: 10.5
  v:
    initial_condition:
      type: gaussian_blobs
      params:
        background:
          sample: uniform
          min: 1.25
          max: 1.62
        generators:
        - count:
            sample: randint
            min: 3
            max: 6
          amplitude:
            sample: uniform
            min: -0.08
            max: 0.16
          sigma:
            sample: uniform
            min: 1.1
            max: 2.1
          aspect_ratio:
            sample: uniform
            min: 1.0
            max: 2.2
          center:
          - sample: uniform
            min: -10.5
            max: 10.5
          - sample: uniform
            min: -10.5
            max: 10.5
boundary_conditions:
  u:
    outer:
    - operator: dirichlet
      value:
        type: constant
        params:
          value: param:u_wall_value
  v:
    outer:
    - operator: dirichlet
      value:
        type: constant
        params:
          value: param:v_wall_value
solver:
  $ref: solver.profile.constant_lhs_scalar_spd
output:
  $ref: output.template.scalar_uv
  formats:
  - numpy
  - gif
  resolution:
  - 176
  - 176
  num_frames: 73
seed: 4250
