preset: navier_stokes
parameters:
  Re:
    sample: uniform
    min: 680.0
    max: 980.0
  k: 1.0
  lower_shear:
    sample: uniform
    min: 1.0
    max: 1.2
  upper_shear:
    sample: uniform
    min: -1.2
    max: -1.0
domain:
  type: rectangle
  size:
  - sample: uniform
    min: 0.98
    max: 1.08
  - sample: uniform
    min: 0.98
    max: 1.08
  mesh_resolution:
  - 192
  - 192
  allow_sampling: true
time:
  dt: 0.0012
  t_end: 0.72
inputs:
  velocity:
    source:
      type: none
      params: {}
    initial_condition:
      components:
        x:
          type: quadrants
          params:
            split:
            - sample: uniform
              min: 0.43
              max: 0.57
            - sample: uniform
              min: 0.45
              max: 0.55
            region_values:
              '00': param:lower_shear
              '01': param:upper_shear
              '10': param:lower_shear
              '11': param:upper_shear
        y:
          type: sine_waves
          params:
            background: 0.0
            modes:
            - amplitude:
                sample: uniform
                min: 0.09
                max: 0.15
              cycles:
              - 6
              - 0
              phase:
                sample: uniform
                min: 0.0
                max: 6.283185
              angle:
                sample: uniform
                min: -0.16
                max: 0.16
            - amplitude:
                sample: uniform
                min: 0.03
                max: 0.08
              cycles:
              - sample: uniform
                min: 3.0
                max: 5.0
              - 0.0
              phase:
                sample: uniform
                min: 0.0
                max: 6.283185
              angle:
                sample: uniform
                min: -0.08
                max: 0.08
boundary_conditions:
  velocity:
    x-:
      - operator: periodic
        pair_with: x+
    x+:
      - operator: periodic
        pair_with: x-
    y-:
      - operator: dirichlet
        value:
          components:
            x:
              type: constant
              params:
                value: param:lower_shear
            y:
              type: constant
              params:
                value: 0.0
    y+:
      - operator: dirichlet
        value:
          components:
            x:
              type: constant
              params:
                value: param:upper_shear
            y:
              type: constant
              params:
                value: 0.0
output:
  $ref: output.template.velocity_pressure
  formats: [numpy, gif]
  resolution:
  - 192
  - 192
  num_frames: 49
solver:
  $ref: solver.profile.transient_mixed_direct
seed: 42
