preset: navier_stokes
parameters:
  Re: 800.0
  k: 1.0
domain:
  type: rectangle
  size:
  - 1.0
  - 1.0
  mesh_resolution:
  - 64
  - 64
time:
  dt: 0.0015
  t_end: 0.75
inputs:
  velocity:
    source:
      type: none
      params: {}
    initial_condition:
      components:
        x:
          type: quadrants
          params:
            split:
            - sample: uniform
              min: 0.42
              max: 0.58
            - sample: uniform
              min: 0.42
              max: 0.58
            region_values:
              '00': 1.0
              '01': -1.0
              '10': 1.0
              '11': -1.0
        y:
          type: sine_waves
          params:
            background: 0.0
            modes:
            - amplitude:
                sample: uniform
                min: 0.0984
                max: 0.1416
              cycles:
              - 6
              - 0
              phase:
                sample: uniform
                min: 0.0
                max: 6.283185
boundary_conditions:
  velocity:
    $ref: boundary_field.vector.periodic_shear_layer_2d
output:
  $ref: output.template.velocity_pressure
  resolution:
  - 128
  - 128
  num_frames: 30
solver:
  $ref: solver.profile.transient_mixed_direct
seed: 42
