preset: advection
parameters: {}
coefficients:
  velocity:
    components:
      x:
        type: sine_waves
        params:
          background: 0.0
          modes:
            - amplitude: 1.25
              cycles: [0.0, 2.0]  # ky: 2.0
              phase: 0.0
      y:
        type: sine_waves
        params:
          background: 0.0
          modes:
            - amplitude: -1.25
              cycles: [2.0, 0.0]  # kx: 2.0
              phase: 0.0
  diffusivity:
    type: constant
    params:
      value: 0.0005
domain:
  type: rectangle
  size:
  - 1.0
  - 1.0
  mesh_resolution:
  - 128
  - 128
time:
  dt: 0.01
  t_end: 2.6
inputs:
  u:
    source:
      type: none
      params: {}
    initial_condition:
      type: gaussian_blobs
      params:
        background: 0.0
        generators:
        - count:
            sample: randint
            min: 1
            max: 2
          amplitude:
            sample: uniform
            min: 0.85
            max: 1.15
          sigma:
            sample: uniform
            min: 0.05
            max: 0.09
          aspect_ratio: 1.0
          center:
          - sample: uniform
            min: 0.205
            max: 0.415
          - sample: uniform
            min: 0.465
            max: 0.675
boundary_conditions:
  u:
    $ref: boundary_field.scalar.full_periodic_2d
solver:
  $ref: solver.profile.constant_lhs_scalar_nonsymmetric
output:
  $ref: output.template.scalar_u
  resolution:
  - 128
  - 128
  num_frames: 53
seed: 42
