preset: advection
parameters: {}
coefficients:
  velocity:
    components:
      x:
        type: sine_waves
        params:
          background: 0.0
          modes:
            - amplitude:
                sample: uniform
                min: 1.06
                max: 1.44
              cycles: [0.0, 2.0]  # ky: 2.0
              phase:
                sample: uniform
                min: -0.3
                max: 0.3
      y:
        type: sine_waves
        params:
          background: 0.0
          modes:
            - amplitude:
                sample: uniform
                min: -1.44
                max: -1.06
              cycles: [2.0, 0.0]  # kx: 2.0
              phase:
                sample: uniform
                min: -0.3
                max: 0.3
  diffusivity:
    type: constant
    params:
      value:
        sample: uniform
        min: 0.00035
        max: 0.0007
domain:
  type: rectangle
  size:
  - 1.0
  - 1.0
  mesh_resolution:
  - 128
  - 128
time:
  dt: 0.01
  t_end: 2.6
inputs:
  u:
    source:
      type: none
      params: {}
    initial_condition:
      type: gaussian_blobs
      params:
        background: 0.0
        generators:
        - count:
            sample: randint
            min: 1
            max: 3
          amplitude:
            sample: uniform
            min: 0.8
            max: 1.2
          sigma:
            sample: uniform
            min: 0.045
            max: 0.095
          aspect_ratio:
            sample: uniform
            min: 1.0
            max: 1.45
          center:
          - sample: uniform
            min: 0.16
            max: 0.44
          - sample: uniform
            min: 0.4
            max: 0.72
boundary_conditions:
  u:
    $ref: boundary_field.scalar.full_periodic_2d
solver:
  $ref: solver.profile.constant_lhs_scalar_nonsymmetric
output:
  $ref: output.template.scalar_u
  resolution:
  - 128
  - 128
  num_frames: 53
seed: 42
