preset: advection
parameters: {}
coefficients:
  velocity:
    components:
      x:
        type: sine_waves
        params:
          background: 0.0
          modes:
            - amplitude: 1.35
              cycles: [0.0, 4.0]
              phase: 0.0
      y:
        type: sine_waves
        params:
          background: 0.0
          modes:
            - amplitude: -1.35
              cycles: [4.0, 0.0]
              phase: 0.0
  diffusivity:
    type: constant
    params:
      value: 0.0001
domain:
  type: rectangle
  size:
  - 1.0
  - 1.0
  mesh_resolution:
  - 128
  - 128
time:
  dt: 0.005
  t_end: 1.6
inputs:
  u:
    source:
      type: none
      params: {}
    initial_condition:
      type: gaussian_blobs
      params:
        background: 0.0
        generators:
        - count: 4
          amplitude: 0.9
          sigma: 0.03
          aspect_ratio: 1.0
          center:
          - sample: uniform
            min: 0.18
            max: 0.82
          - sample: uniform
            min: 0.18
            max: 0.82
boundary_conditions:
  u:
    $ref: boundary_field.scalar.full_periodic_2d
solver:
  $ref: solver.profile.constant_lhs_scalar_nonsymmetric
output:
  $ref: output.template.scalar_u
  resolution:
  - 128
  - 128
  num_frames: 61
seed: 42
