preset: advection
parameters: {}
coefficients:
  velocity:
    components:
      x:
        type: affine
        params:
          constant:
            sample: uniform
            min: -1.24
            max: -0.96
          y:
            sample: uniform
            min: 1.9
            max: 2.5
      y:
        type: affine
        params:
          constant:
            sample: uniform
            min: 0.96
            max: 1.24
          x:
            sample: uniform
            min: -2.5
            max: -1.9
  diffusivity:
    type: constant
    params:
      value:
        sample: uniform
        min: 0.00028
        max: 0.00055
domain:
  type: rectangle
  size:
  - 1.0
  - 1.0
  mesh_resolution:
  - 128
  - 128
time:
  dt: 0.01
  t_end: 3.0
inputs:
  u:
    source:
      type: none
      params: {}
    initial_condition:
      type: gaussian_blobs
      params:
        background: 0.0
        generators:
        - count:
            sample: randint
            min: 1
            max: 2
          amplitude:
            sample: uniform
            min: 0.85
            max: 1.15
          sigma:
            sample: uniform
            min: 0.015
            max: 0.055
          aspect_ratio:
            sample: uniform
            min: 1.0
            max: 1.35
          center:
          - sample: uniform
            min: 0.7
            max: 0.86
          - sample: uniform
            min: 0.34
            max: 0.5
boundary_conditions:
  u:
    x-:
    - operator: neumann
      value:
        type: constant
        params:
          value:
            sample: uniform
            min: -0.008
            max: 0.008
    x+:
    - operator: neumann
      value:
        type: constant
        params:
          value:
            sample: uniform
            min: -0.008
            max: 0.008
    y-:
    - operator: neumann
      value:
        type: constant
        params:
          value:
            sample: uniform
            min: -0.008
            max: 0.008
    y+:
    - operator: neumann
      value:
        type: constant
        params:
          value:
            sample: uniform
            min: -0.008
            max: 0.008
solver:
  $ref: solver.profile.constant_lhs_scalar_nonsymmetric
output:
  $ref: output.template.scalar_u
  resolution:
  - 128
  - 128
  num_frames: 61
seed: 42
