preset: cahn_hilliard
parameters:
  lmbda: 0.01
  barrier_height: 100.0
  mobility: 1.0
  theta: 0.5
domain:
  type: rectangle
  size: [1.0, 1.0]
  mesh_resolution: [96, 96]
time:
  dt: 5.0e-06
  t_end: 2.5e-04
inputs:
  c:
    initial_condition:
      type: random_perturbation
      params:
        mean: 0.63
        std: 0.02
boundary_conditions:
  c:
    x-:
      - operator: periodic
        pair_with: x+
    x+:
      - operator: periodic
        pair_with: x-
    y-:
      - operator: periodic
        pair_with: y+
    y+:
      - operator: periodic
        pair_with: y-
output:
  path: ./output
  resolution: [64, 64]
  num_frames: 20
  formats: [numpy, gif]
  fields:
    c: scalar
solver:
  snes_type: newtonls
  snes_linesearch_type: "none"
  ksp_type: preonly
  pc_type: lu
seed: 42
