preset: cahn_hilliard
parameters:
  lmbda:
    sample: uniform
    min: 0.005
    max: 0.008
  barrier_height:
    sample: uniform
    min: 80.0
    max: 130.0
  mobility:
    sample: uniform
    min: 0.4
    max: 0.9
  theta:
    sample: uniform
    min: 0.84
    max: 1.0
domain:
  allow_sampling: true
  type: parallelogram
  origin: [0.0, 0.0]
  axis_x:
    - sample: uniform
      min: 0.96
      max: 1.08
    - 0.0
  axis_y:
    - sample: uniform
      min: 0.16
      max: 0.34
    - sample: uniform
      min: 0.94
      max: 1.08
  mesh_resolution: [128, 128]
time:
  dt: 2.0e-06
  t_end: 2.4e-04
inputs:
  c:
    initial_condition:
      type: gaussian_noise
      params:
        mean:
          sample: uniform
          min: 0.44
          max: 0.58
        std:
          sample: uniform
          min: 0.02
          max: 0.045
boundary_conditions:
  c:
    $ref: boundary_field.scalar.full_periodic_2d
output:
  $ref: output.template.scalar_c
  formats: [numpy, gif]
  resolution: [160, 128]
  num_frames: 33
solver:
  $ref: solver.profile.nonlinear_mixed_direct_bt
seed: 42
