preset: cahn_hilliard
parameters:
  lmbda: 0.02
  barrier_height: 100.0
  mobility: 1.0
  theta: 0.5
domain:
  type: box
  size: [1.0, 1.0, 1.0]
  mesh_resolution: [16, 16, 16]
time:
  dt: 5.0e-06
  t_end: 2.5e-04
fields:
  c:
    initial_condition:
      type: random_perturbation
      params:
        mean: 0.63
        std: 0.02
    output: scalar
output:
  path: ./output
  resolution: [16, 16, 16]
  num_frames: 5
  formats: [numpy]
solver:
  snes_type: newtonls
  snes_linesearch_type: "none"
  ksp_type: preonly
  pc_type: lu
seed: 42
