preset: cahn_hilliard

parameters:
  lmbda: 0.02
  barrier_height: 100.0
  mobility: 1.0
  theta: 0.5

domain:
  type: box
  size: [1.0, 1.0, 1.0]
  mesh_resolution: [16, 16, 16]

boundary_conditions:
  c: {}

source_terms:
  c:
    type: none

initial_conditions:
  c:
    type: random_perturbation
    params:
      mean: 0.63
      std: 0.02

dt: 5.0e-06
t_end: 2.5e-04

output_resolution: [16, 16, 16]
output:
  path: ./output
  num_frames: 5
  formats: [numpy]

solver:
  snes_type: newtonls
  snes_linesearch_type: "none"
  ksp_type: preonly
  pc_type: lu

seed: 42
