"""Solver strategy identifiers and shared classification helpers."""

CONSTANT_LHS_SCALAR_SPD = "constant_lhs_scalar_spd"
CONSTANT_LHS_SCALAR_NONSYMMETRIC = "constant_lhs_scalar_nonsymmetric"
TRANSIENT_SADDLE_POINT = "transient_saddle_point"
TRANSIENT_MIXED_DIRECT = "transient_mixed_direct"
NONLINEAR_MIXED_DIRECT = "nonlinear_mixed_direct"
TRANSIENT_EXPLICIT = "transient_explicit"
CONSTANT_LHS_CURL_DIRECT = "constant_lhs_curl_direct"
CONSTANT_LHS_BLOCK_DIRECT = "constant_lhs_block_direct"

CONSTANT_LHS_STRATEGIES = {
    CONSTANT_LHS_SCALAR_SPD,
    CONSTANT_LHS_SCALAR_NONSYMMETRIC,
    CONSTANT_LHS_CURL_DIRECT,
    CONSTANT_LHS_BLOCK_DIRECT,
}

NESTED_MIXED_STRATEGIES = {
    TRANSIENT_SADDLE_POINT,
}

ALL_SOLVER_STRATEGIES = {
    CONSTANT_LHS_SCALAR_SPD,
    CONSTANT_LHS_SCALAR_NONSYMMETRIC,
    TRANSIENT_SADDLE_POINT,
    TRANSIENT_MIXED_DIRECT,
    NONLINEAR_MIXED_DIRECT,
    TRANSIENT_EXPLICIT,
    CONSTANT_LHS_CURL_DIRECT,
    CONSTANT_LHS_BLOCK_DIRECT,
}
